### ISSUE TITLE
Lichess database

### ISSUE THREAD

**Issue by pnodet** [Assios/chessguessr#11]
Hi @Assios and congrats for the work 🎉

I am one of the maintainer of [chesspecker](https://www.chesspecker.com) an open-source training app.

I don't know if you are aware of the lichess puzzle [database](https://database.lichess.org/#puzzles) that provide everyone with currently 2,776,334 puzzles. It's a great opportunity to streamline your process and add a new feature: allowing users to play infinite rounds of chessguessr.

It would be a fun addition to your already great website!

If you have storage problems we could discuss about providing you to our mongo db storing the puzzles.

**Comment by Assios** [comment]
Hey, thank you @pnxdxt!

I am aware of the Lichess puzzle database. For the daily Geoguessr puzzles I'm just curating the puzzles manually, since I don't want all of the Chessguessr puzzles to only have only one winning line. I also want there to be one daily puzzle to solve, just like other Wordle-like games.

Having different modes, however, is a good idea. I'm envisioning something like Lichess Puzzle Streak, where you solve Chessguessr's until you fail. For this, I would probably need to use regular puzzles from the database.

Thanks for your input, I'm leaving the issue open for now.
