### ISSUE TITLE
Correct move shown in red color because it does not come with check.

### ISSUE THREAD

**Issue by asdfjasdf** [Assios/chessguessr#19]
In today's puzzle I moved "Ng5" and it showed up in red (i.e. correct piece but wrong move). However, it turned out that the move was correct (and in the correct spot) but in my line didn't come with check, i.e. in the solution the move was "Ng5+". Is this behavior intentional? Personally, I would have expected the move to be shown as correct (i.e. in green color) in this case, but that is certainly debatable.

**Comment by Assios** [comment]
Hi! This is intentional, the notation has to be identical for it to be considered the same move. It is, as you say, debatable whether this is the best solution. I came to the conclusion that the requirement for the notation to be identical was the most clear-cut way to do it. Otherwise, you would have to define whether captures and non-captures are also the same move.

This decision is not final, however, and I am open to other suggestions. For now, I will add a section explaining that the notation has to be identical for the moves to be considered the same in the "How to play" modal. Thanks for the feedback!
